const FETCH_EXERCISES = 'FETCH_EXERCISES';
const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS';
const FETCH_EXERCISES_ERRROR = 'FETCH_EXERCISES_ERRROR';

export default {
  FETCH_EXERCISES,
  FETCH_EXERCISES_SUCCESS,
  FETCH_EXERCISES_ERRROR
};
